#include <string>
#include <vector>

enum class Item {
    RETRY,

    //Jokers
    J_BEGIN,

    J_C_BEGIN,
    Joker,
    Greedy_Joker,
    Lusty_Joker,
    Wrathful_Joker,
    Gluttonous_Joker,
    Jolly_Joker,
    Zany_Joker,
    Mad_Joker,
    Crazy_Joker,
    Droll_Joker,
    Sly_Joker,
    Wily_Joker,
    Clever_Joker,
    Devious_Joker,
    Crafty_Joker,
    Half_Joker,
    Credit_Card,
    Banner,
    Mystic_Summit,
    _8_Ball,
    Misprint,
    Raised_Fist,
    Chaos_the_Clown,
    Scary_Face,
    Abstract_Joker,
    Delayed_Gratification,
    Gros_Michel,
    Even_Steven,
    Odd_Todd,
    Scholar,
    Business_Card,
    Supernova,
    Ride_the_Bus,
    Egg,
    Runner,
    Ice_Cream,
    Splash,
    Blue_Joker,
    Faceless_Joker,
    Green_Joker,
    Superposition,
    To_Do_List,
    Cavendish,
    Red_Card,
    Square_Joker,
    Riff_raff,
    Photograph,
    Reserved_Parking,
    Mail_In_Rebate,
    Hallucination,
    Fortune_Teller,
    Juggler,
    Drunkard,
    Golden_Joker,
    Popcorn,
    Walkie_Talkie,
    Smiley_Face,
    Golden_Ticket,
    Swashbuckler,
    Hanging_Chad,
    Shoot_the_Moon,
    J_C_END,

    J_U_BEGIN,
    Joker_Stencil,
    Four_Fingers,
    Mime,
    Ceremonial_Dagger,
    Marble_Joker,
    Loyalty_Card,
    Dusk,
    Fibonacci,
    Steel_Joker,
    Hack,
    Pareidolia,
    Space_Joker,
    Burglar,
    Blackboard,
    Sixth_Sense,
    Constellation,
    Hiker,
    Card_Sharp,
    Madness,
    Seance,
    Shortcut,
    Hologram,
    Cloud_9,
    Rocket,
    Midas_Mask,
    Luchador,
    Gift_Card,
    Turtle_Bean,
    Erosion,
    To_the_Moon,
    Stone_Joker,
    Lucky_Cat,
    Bull,
    Diet_Cola,
    Trading_Card,
    Flash_Card,
    Spare_Trousers,
    Ramen,
    Seltzer,
    Castle,
    Mr_Bones,
    Acrobat,
    Sock_and_Buskin,
    Troubadour,
    Certificate,
    Smeared_Joker,
    Throwback,
    Rough_Gem,
    Bloodstone,
    Arrowhead,
    Onyx_Agate,
    Glass_Joker,
    Showman,
    Flower_Pot,
    Merry_Andy,
    Oops_All_6s,
    The_Idol,
    Seeing_Double,
    Matador,
    Stuntman,
    Satellite,
    Cartomancer,
    Astronomer,
    Bootstraps,
    J_U_END,

    J_R_BEGIN,
    DNA,
    Vampire,
    Vagabond,
    Baron,
    Obelisk,
    Baseball_Card,
    Ancient_Joker,
    Campfire,
    Blueprint,
    Wee_Joker,
    Hit_the_Road,
    The_Duo,
    The_Trio,
    The_Family,
    The_Order,
    The_Tribe,
    Invisible_Joker,
    Brainstorm,
    Drivers_License,
    Burnt_Joker,
    J_R_END,

    J_L_BEGIN,
    Canio,
    Triboulet,
    Yorick,
    Chicot,
    Perkeo,
    J_L_END,

    J_END,

    // Vouchers
    V_BEGIN,
    Overstock,
    Overstock_Plus,
    Clearance_Sale,
    Liquidation,
    Hone,
    Glow_Up,
    Reroll_Surplus,
    Reroll_Glut,
    Crystal_Ball,
    Omen_Globe,
    Telescope,
    Observatory,
    Grabber,
    Nacho_Tong,
    Wasteful,
    Recyclomancy,
    Tarot_Merchant,
    Tarot_Tycoon,
    Planet_Merchant,
    Planet_Tycoon,
    Seed_Money,
    Money_Tree,
    Blank,
    Antimatter,
    Magic_Trick,
    Illusion,
    Hieroglyph,
    Petroglyph,
    Directors_Cut,
    Retcon,
    Paint_Brush,
    Palette,
    V_END,

    // Tarots
    T_BEGIN,
    The_Fool,
    The_Magician,
    The_High_Priestess,
    The_Empress,
    The_Emperor,
    The_Hierophant,
    The_Lovers,
    The_Chariot,
    Justice,
    The_Hermit,
    The_Wheel_of_Fortune,
    Strength,
    The_Hanged_Man,
    Death,
    Temperance,
    The_Devil,
    The_Tower,
    The_Star,
    The_Moon,
    The_Sun,
    Judgement,
    The_World,
    T_END,

    // Planets
    P_BEGIN,
    Mercury,
    Venus,
    Earth,
    Mars,
    Jupiter,
    Saturn,
    Uranus,
    Neptune,
    Pluto,
    Planet_X,
    Ceres,
    Eris,
    P_END,

    // Hands
    H_BEGIN,
    Pair,
    Three_of_a_Kind,
    Full_House,
    Four_of_a_Kind,
    Flush,
    Straight,
    Two_Pair,
    Straight_Flush,
    High_Card,
    Five_of_a_Kind,
    Flush_House,
    Flush_Five,
    H_END,

    // Spectrals
    S_BEGIN,
    Familiar,
    Grim,
    Incantation,
    Talisman,
    Aura,
    Wraith,
    Sigil,
    Ouija,
    Ectoplasm,
    Immolate,
    Ankh,
    Deja_Vu,
    Hex,
    Trance,
    Medium,
    Cryptid,
    The_Soul,
    Black_Hole,
    S_END,

    // Enhancements
    ENHANCEMENT_BEGIN,
    No_Enhancement,
    Bonus_Card,
    Mult_Card,
    Wild_Card,
    Glass_Card,
    Steel_Card,
    Stone_Card,
    Gold_Card,
    Lucky_Card,
    ENHANCEMENT_END,

    // Seals
    SEAL_BEGIN,
    No_Seal,
    Gold_Seal,
    Red_Seal,
    Blue_Seal,
    Purple_Seal,
    SEAL_END,

    // Editions
    E_BEGIN,
    No_Edition,
    Foil,
    Holographic,
    Polychrome,
    Negative,
    E_END,

    // Booster Packs
    PACK_BEGIN,
    Arcana_Pack,
    Jumbo_Arcana_Pack,
    Mega_Arcana_Pack,
    Celestial_Pack,
    Jumbo_Celestial_Pack,
    Mega_Celestial_Pack,
    Standard_Pack,
    Jumbo_Standard_Pack,
    Mega_Standard_Pack,
    Buffoon_Pack,
    Jumbo_Buffoon_Pack,
    Mega_Buffoon_Pack,
    Spectral_Pack,
    Jumbo_Spectral_Pack,
    Mega_Spectral_Pack,
    PACK_END,

    // Tags
    TAG_BEGIN,
    Uncommon_Tag,
    Rare_Tag,
    Negative_Tag,
    Foil_Tag,
    Holographic_Tag,
    Polychrome_Tag,
    Investment_Tag,
    Voucher_Tag,
    Boss_Tag,
    Standard_Tag,
    Charm_Tag,
    Meteor_Tag,
    Buffoon_Tag,
    Handy_Tag,
    Garbage_Tag,
    Ethereal_Tag,
    Coupon_Tag,
    Double_Tag,
    Juggle_Tag,
    D6_Tag,
    Top_up_Tag,
    Speed_Tag,
    Orbital_Tag,
    Economy_Tag,
    TAG_END,

    // Blinds
    B_BEGIN,
    Small_Blind,
    Big_Blind,
    The_Hook,
    The_Ox,
    The_House,
    The_Wall,
    The_Wheel,
    The_Arm,
    The_Club,
    The_Fish,
    The_Psychic,
    The_Goad,
    The_Water,
    The_Window,
    The_Manacle,
    The_Eye,
    The_Mouth,
    The_Plant,
    The_Serpent,
    The_Pillar,
    The_Needle,
    The_Head,
    The_Tooth,
    The_Flint,
    The_Mark,
    B_F_BEGIN,
    Amber_Acorn,
    Verdant_Leaf,
    Violet_Vessel,
    Crimson_Heart,
    Cerulean_Bell,
    B_F_END,
    B_END,

    // Suits
    SUIT_BEGIN,
    Hearts,
    Clubs,
    Diamonds,
    Spades,
    SUIT_END,

    // Ranks
    RANK_BEGIN,
    _2,
    _3,
    _4,
    _5,
    _6,
    _7,
    _8,
    _9,
    _10,
    Jack,
    Queen,
    King,
    Ace,
    RANK_END,

    // Cards
    C_BEGIN,
    C_2,
    C_3,
    C_4,
    C_5,
    C_6,
    C_7,
    C_8,
    C_9,
    C_A,
    C_J,
    C_K,
    C_Q,
    C_T,
    D_2,
    D_3,
    D_4,
    D_5,
    D_6,
    D_7,
    D_8,
    D_9,
    D_A,
    D_J,
    D_K,
    D_Q,
    D_T,
    H_2,
    H_3,
    H_4,
    H_5,
    H_6,
    H_7,
    H_8,
    H_9,
    H_A,
    H_J,
    H_K,
    H_Q,
    H_T,
    S_2,
    S_3,
    S_4,
    S_5,
    S_6,
    S_7,
    S_8,
    S_9,
    S_A,
    S_J,
    S_K,
    S_Q,
    S_T,
    C_END,

    // Decks
    D_BEGIN,
    Red_Deck,
    Blue_Deck,
    Yellow_Deck,
    Green_Deck,
    Black_Deck,
    Magic_Deck,
    Nebula_Deck,
    Ghost_Deck,
    Abandoned_Deck,
    Checkered_Deck,
    Zodiac_Deck,
    Painted_Deck,
    Anaglyph_Deck,
    Plasma_Deck,
    Erratic_Deck,
    Challenge_Deck,
    D_END,

    // Challenges
    CHAL_BEGIN,
    The_Omelette,
    _15_Minute_City,
    Rich_get_Richer,
    On_a_Knifes_Edge,
    X_ray_Vision,
    Mad_World,
    Luxury_Tax,
    Non_Perishable,
    Medusa,
    Double_or_Nothing,
    Typecast,
    Inflation,
    Bram_Poker,
    Fragile,
    Monolith,
    Blast_Off,
    Five_Card_Draw,
    Golden_Needle,
    Cruelty,
    Jokerless,
    CHAL_END,

    //Stakes
    STAKE_BEGIN,
    White_Stake,
    Red_Stake,
    Green_Stake,
    Black_Stake,
    Blue_Stake,
    Purple_Stake,
    Orange_Stake,
    Gold_Stake,
    STAKE_END,

    RARITY_BEGIN,
    Common,
    Uncommon,
    Rare,
    Legendary,
    RARITY_END,

    TYPE_BEGIN,
    T_Joker,
    T_Tarot,
    T_Planet,
    T_Spectral,
    T_Playing_Card,
    TYPE_END,

    ITEMS_END
};

// Structs for storing information
struct ShopInstance {
    double jokerRate;
    double tarotRate;
    double planetRate;
    double playingCardRate;
    double spectralRate;
    ShopInstance() {
        jokerRate = 20;
        tarotRate = 4;
        planetRate = 4;
        playingCardRate = 0;
        spectralRate = 0;
    };
    ShopInstance(double j, double t, double p, double c, double s) {
        jokerRate = j;
        tarotRate = t;
        planetRate = p;
        playingCardRate = c;
        spectralRate = s;
    }
    double getTotalRate() {
        return jokerRate + tarotRate + planetRate + playingCardRate + spectralRate;
    }
};

struct JokerStickers {
    bool eternal;
    bool perishable;
    bool rental;
    JokerStickers() {
        eternal = false;
        perishable = false;
        rental = false;
    };
    JokerStickers(bool e, bool p, bool r) {
        eternal = e;
        perishable = p;
        rental = r;
    }
};

struct JokerData {
    Item joker;
    Item rarity;
    Item edition;
    JokerStickers stickers;
    JokerData() {
        joker = Item::Joker;
        rarity = Item::Common;
        edition = Item::No_Edition;
        stickers = JokerStickers();
    };
    JokerData(Item j, Item r, Item e, JokerStickers s) {
        joker = j;
        rarity = r;
        edition = e;
        stickers = s;
    };
};

struct ShopItem {
    Item type;
    Item item;
    JokerData jokerData;
    ShopItem() {
        type = Item::T_Tarot;
        item = Item::The_Fool;
    };
    ShopItem(Item t, Item i) {
        type = t;
        item = i;
    };
    ShopItem(Item t, Item i, JokerData j) {
        type = t;
        item = i;
        jokerData = j;
    };
};

struct WeightedItem {
    Item item;
    double weight;
    WeightedItem(Item i, double w) {
        item = i;
        weight = w;
    };
};

struct Pack {
    Item type;
    int size;
    int choices;
    Pack(Item t, int s, int c) {
        type = t;
        size = s;
        choices = c;
    }
};

struct Card {
    Item base;
    Item enhancement;
    Item edition;
    Item seal;
    Card(Item b, Item n, Item e, Item s) {
        base = b;
        enhancement = n;
        edition = e;
        seal = s;
    }
};

std::vector<Item> ENHANCEMENTS = {
    Item::Bonus_Card,
    Item::Mult_Card,
    Item::Wild_Card,
    Item::Glass_Card,
    Item::Steel_Card,
    Item::Stone_Card,
    Item::Gold_Card,
    Item::Lucky_Card
};

std::vector<Item> CARDS = { 
    Item::C_2,
    Item::C_3,
    Item::C_4,
    Item::C_5,
    Item::C_6,
    Item::C_7,
    Item::C_8,
    Item::C_9,
    Item::C_A,
    Item::C_J,
    Item::C_K,
    Item::C_Q,
    Item::C_T,
    Item::D_2,
    Item::D_3,
    Item::D_4,
    Item::D_5,
    Item::D_6,
    Item::D_7,
    Item::D_8,
    Item::D_9,
    Item::D_A,
    Item::D_J,
    Item::D_K,
    Item::D_Q,
    Item::D_T,
    Item::H_2,
    Item::H_3,
    Item::H_4,
    Item::H_5,
    Item::H_6,
    Item::H_7,
    Item::H_8,
    Item::H_9,
    Item::H_A,
    Item::H_J,
    Item::H_K,
    Item::H_Q,
    Item::H_T,
    Item::S_2,
    Item::S_3,
    Item::S_4,
    Item::S_5,
    Item::S_6,
    Item::S_7,
    Item::S_8,
    Item::S_9,
    Item::S_A,
    Item::S_J,
    Item::S_K,
    Item::S_Q,
    Item::S_T
};

std::vector<Item> SUITS = {
    Item::Spades,
    Item::Hearts,
    Item::Clubs,
    Item::Diamonds
};

std::vector<Item> RANKS = {
    Item::_2,
    Item::_3,
    Item::_4,
    Item::_5,
    Item::_6,
    Item::_7,
    Item::_8,
    Item::_9,
    Item::_10,
    Item::Jack,
    Item::Queen,
    Item::King,
    Item::Ace
};

std::vector<WeightedItem> PACKS = {
    WeightedItem(Item::RETRY, 22.42), //total
    WeightedItem(Item::Arcana_Pack, 4),
    WeightedItem(Item::Jumbo_Arcana_Pack, 2),
    WeightedItem(Item::Mega_Arcana_Pack, 0.5),
    WeightedItem(Item::Celestial_Pack, 4),
    WeightedItem(Item::Jumbo_Celestial_Pack, 2),
    WeightedItem(Item::Mega_Celestial_Pack, 0.5),
    WeightedItem(Item::Standard_Pack, 4),
    WeightedItem(Item::Jumbo_Standard_Pack, 2),
    WeightedItem(Item::Mega_Standard_Pack, 0.5),
    WeightedItem(Item::Buffoon_Pack, 1.2),
    WeightedItem(Item::Jumbo_Buffoon_Pack, 0.6),
    WeightedItem(Item::Mega_Buffoon_Pack, 0.15),
    WeightedItem(Item::Spectral_Pack, 0.6),
    WeightedItem(Item::Jumbo_Spectral_Pack, 0.3),
    WeightedItem(Item::Mega_Spectral_Pack, 0.07)
};

std::vector<Item> TAROTS = {
    Item::The_Fool,
    Item::The_Magician,
    Item::The_High_Priestess,
    Item::The_Empress,
    Item::The_Emperor,
    Item::The_Hierophant,
    Item::The_Lovers,
    Item::The_Chariot,
    Item::Justice,
    Item::The_Hermit,
    Item::The_Wheel_of_Fortune,
    Item::Strength,
    Item::The_Hanged_Man,
    Item::Death,
    Item::Temperance,
    Item::The_Devil,
    Item::The_Tower,
    Item::The_Star,
    Item::The_Moon,
    Item::The_Sun,
    Item::Judgement,
    Item::The_World
};

std::vector<Item> PLANETS = {
    Item::Mercury,
    Item::Venus,
    Item::Earth,
    Item::Mars,
    Item::Jupiter,
    Item::Saturn,
    Item::Uranus,
    Item::Neptune,
    Item::Pluto,
    Item::Planet_X,
    Item::Ceres,
    Item::Eris
};

std::vector<Item> COMMON_JOKERS_100 = {
    Item::Joker,
    Item::Greedy_Joker,
    Item::Lusty_Joker,
    Item::Wrathful_Joker,
    Item::Gluttonous_Joker,
    Item::Jolly_Joker,
    Item::Zany_Joker,
    Item::Mad_Joker,
    Item::Crazy_Joker,
    Item::Droll_Joker,
    Item::Sly_Joker,
    Item::Wily_Joker,
    Item::Clever_Joker,
    Item::Devious_Joker,
    Item::Crafty_Joker,
    Item::Half_Joker,
    Item::Credit_Card,
    Item::Banner,
    Item::Mystic_Summit,
    Item::_8_Ball,
    Item::Misprint,
    Item::Raised_Fist,
    Item::Chaos_the_Clown,
    Item::Scary_Face,
    Item::Abstract_Joker,
    Item::Delayed_Gratification,
    Item::Gros_Michel,
    Item::Even_Steven,
    Item::Odd_Todd,
    Item::Scholar,
    Item::Business_Card,
    Item::Supernova,
    Item::Ride_the_Bus,
    Item::Egg,
    Item::Runner,
    Item::Ice_Cream,
    Item::Splash,
    Item::Blue_Joker,
    Item::Faceless_Joker,
    Item::Green_Joker,
    Item::Superposition,
    Item::To_Do_List,
    Item::Cavendish,
    Item::Red_Card,
    Item::Square_Joker,
    Item::Riff_raff,
    Item::Photograph,
    Item::Mail_In_Rebate,
    Item::Hallucination,
    Item::Fortune_Teller,
    Item::Juggler,
    Item::Drunkard,
    Item::Golden_Joker,
    Item::Popcorn,
    Item::Walkie_Talkie,
    Item::Smiley_Face,
    Item::Golden_Ticket,
    Item::Swashbuckler,
    Item::Hanging_Chad,
    Item::Shoot_the_Moon
};

std::vector<Item> COMMON_JOKERS = {
    Item::Joker,
    Item::Greedy_Joker,
    Item::Lusty_Joker,
    Item::Wrathful_Joker,
    Item::Gluttonous_Joker,
    Item::Jolly_Joker,
    Item::Zany_Joker,
    Item::Mad_Joker,
    Item::Crazy_Joker,
    Item::Droll_Joker,
    Item::Sly_Joker,
    Item::Wily_Joker,
    Item::Clever_Joker,
    Item::Devious_Joker,
    Item::Crafty_Joker,
    Item::Half_Joker,
    Item::Credit_Card,
    Item::Banner,
    Item::Mystic_Summit,
    Item::_8_Ball,
    Item::Misprint,
    Item::Raised_Fist,
    Item::Chaos_the_Clown,
    Item::Scary_Face,
    Item::Abstract_Joker,
    Item::Delayed_Gratification,
    Item::Gros_Michel,
    Item::Even_Steven,
    Item::Odd_Todd,
    Item::Scholar,
    Item::Business_Card,
    Item::Supernova,
    Item::Ride_the_Bus,
    Item::Egg,
    Item::Runner,
    Item::Ice_Cream,
    Item::Splash,
    Item::Blue_Joker,
    Item::Faceless_Joker,
    Item::Green_Joker,
    Item::Superposition,
    Item::To_Do_List,
    Item::Cavendish,
    Item::Red_Card,
    Item::Square_Joker,
    Item::Riff_raff,
    Item::Photograph,
    Item::Reserved_Parking,
    Item::Mail_In_Rebate,
    Item::Hallucination,
    Item::Fortune_Teller,
    Item::Juggler,
    Item::Drunkard,
    Item::Golden_Joker,
    Item::Popcorn,
    Item::Walkie_Talkie,
    Item::Smiley_Face,
    Item::Golden_Ticket,
    Item::Swashbuckler,
    Item::Hanging_Chad,
    Item::Shoot_the_Moon,
};

std::vector<Item> UNCOMMON_JOKERS_100 = {
    Item::Joker_Stencil,
    Item::Four_Fingers,
    Item::Mime,
    Item::Ceremonial_Dagger,
    Item::Marble_Joker,
    Item::Loyalty_Card,
    Item::Dusk,
    Item::Fibonacci,
    Item::Steel_Joker,
    Item::Hack,
    Item::Pareidolia,
    Item::Space_Joker,
    Item::Burglar,
    Item::Blackboard,
    Item::Constellation,
    Item::Hiker,
    Item::Card_Sharp,
    Item::Madness,
    Item::Vampire,
    Item::Shortcut,
    Item::Hologram,
    Item::Vagabond,
    Item::Cloud_9,
    Item::Rocket,
    Item::Midas_Mask,
    Item::Luchador,
    Item::Gift_Card,
    Item::Turtle_Bean,
    Item::Erosion,
    Item::Reserved_Parking,
    Item::To_the_Moon,
    Item::Stone_Joker,
    Item::Lucky_Cat,
    Item::Bull,
    Item::Diet_Cola,
    Item::Trading_Card,
    Item::Flash_Card,
    Item::Spare_Trousers,
    Item::Ramen,
    Item::Seltzer,
    Item::Castle,
    Item::Mr_Bones,
    Item::Acrobat,
    Item::Sock_and_Buskin,
    Item::Troubadour,
    Item::Certificate,
    Item::Smeared_Joker,
    Item::Throwback,
    Item::Rough_Gem,
    Item::Bloodstone,
    Item::Arrowhead,
    Item::Onyx_Agate,
    Item::Glass_Joker,
    Item::Showman,
    Item::Flower_Pot,
    Item::Merry_Andy,
    Item::Oops_All_6s,
    Item::The_Idol,
    Item::Seeing_Double,
    Item::Matador,
    Item::Stuntman,
    Item::Satellite,
    Item::Cartomancer,
    Item::Astronomer,
    Item::Burnt_Joker,
    Item::Bootstraps
};

std::vector<Item> UNCOMMON_JOKERS = {
    Item::Joker_Stencil,
    Item::Four_Fingers,
    Item::Mime,
    Item::Ceremonial_Dagger,
    Item::Marble_Joker,
    Item::Loyalty_Card,
    Item::Dusk,
    Item::Fibonacci,
    Item::Steel_Joker,
    Item::Hack,
    Item::Pareidolia,
    Item::Space_Joker,
    Item::Burglar,
    Item::Blackboard,
    Item::Sixth_Sense,
    Item::Constellation,
    Item::Hiker,
    Item::Card_Sharp,
    Item::Madness,
    Item::Seance,
    Item::Vampire,
    Item::Shortcut,
    Item::Hologram,
    Item::Cloud_9,
    Item::Rocket,
    Item::Midas_Mask,
    Item::Luchador,
    Item::Gift_Card,
    Item::Turtle_Bean,
    Item::Erosion,
    Item::To_the_Moon,
    Item::Stone_Joker,
    Item::Lucky_Cat,
    Item::Bull,
    Item::Diet_Cola,
    Item::Trading_Card,
    Item::Flash_Card,
    Item::Spare_Trousers,
    Item::Ramen,
    Item::Seltzer,
    Item::Castle,
    Item::Mr_Bones,
    Item::Acrobat,
    Item::Sock_and_Buskin,
    Item::Troubadour,
    Item::Certificate,
    Item::Smeared_Joker,
    Item::Throwback,
    Item::Rough_Gem,
    Item::Bloodstone,
    Item::Arrowhead,
    Item::Onyx_Agate,
    Item::Glass_Joker,
    Item::Showman,
    Item::Flower_Pot,
    Item::Merry_Andy,
    Item::Oops_All_6s,
    Item::The_Idol,
    Item::Seeing_Double,
    Item::Matador,
    Item::Satellite,
    Item::Cartomancer,
    Item::Astronomer,
    Item::Bootstraps,
};

std::vector<Item> RARE_JOKERS_100 = {
    Item::DNA,
    Item::Sixth_Sense,
    Item::Seance,
    Item::Baron,
    Item::Obelisk,
    Item::Baseball_Card,
    Item::Ancient_Joker,
    Item::Campfire,
    Item::Blueprint,
    Item::Wee_Joker,
    Item::Hit_the_Road,
    Item::The_Duo,
    Item::The_Trio,
    Item::The_Family,
    Item::The_Order,
    Item::The_Tribe,
    Item::Invisible_Joker,
    Item::Brainstorm,
    Item::Drivers_License
};


std::vector<Item> RARE_JOKERS = {
    Item::DNA,
    Item::Vagabond,
    Item::Baron,
    Item::Obelisk,
    Item::Baseball_Card,
    Item::Ancient_Joker,
    Item::Campfire,
    Item::Blueprint,
    Item::Wee_Joker,
    Item::Hit_the_Road,
    Item::The_Duo,
    Item::The_Trio,
    Item::The_Family,
    Item::The_Order,
    Item::The_Tribe,
    Item::Stuntman,
    Item::Invisible_Joker,
    Item::Brainstorm,
    Item::Drivers_License,
    Item::Burnt_Joker,
};

std::vector<Item> LEGENDARY_JOKERS = {
    Item::Canio,
    Item::Triboulet,
    Item::Yorick,
    Item::Chicot,
    Item::Perkeo
};

std::vector<Item> VOUCHERS = {
    Item::Overstock,
    Item::Overstock_Plus,
    Item::Clearance_Sale,
    Item::Liquidation,
    Item::Hone,
    Item::Glow_Up,
    Item::Reroll_Surplus,
    Item::Reroll_Glut,
    Item::Crystal_Ball,
    Item::Omen_Globe,
    Item::Telescope,
    Item::Observatory,
    Item::Grabber,
    Item::Nacho_Tong,
    Item::Wasteful,
    Item::Recyclomancy,
    Item::Tarot_Merchant,
    Item::Tarot_Tycoon,
    Item::Planet_Merchant,
    Item::Planet_Tycoon,
    Item::Seed_Money,
    Item::Money_Tree,
    Item::Blank,
    Item::Antimatter,
    Item::Magic_Trick,
    Item::Illusion,
    Item::Hieroglyph,
    Item::Petroglyph,
    Item::Directors_Cut,
    Item::Retcon,
    Item::Paint_Brush,
    Item::Palette
};

std::vector<Item> SPECTRALS = {
    Item::Familiar,
    Item::Grim,
    Item::Incantation,
    Item::Talisman,
    Item::Aura,
    Item::Wraith,
    Item::Sigil,
    Item::Ouija,
    Item::Ectoplasm,
    Item::Immolate,
    Item::Ankh,
    Item::Deja_Vu,
    Item::Hex,
    Item::Trance,
    Item::Medium,
    Item::Cryptid,
    Item::RETRY, //Soul
    Item::RETRY //Black_Hole
};

std::vector<Item> TAGS = {
    Item::Uncommon_Tag,
    Item::Rare_Tag,
    Item::Negative_Tag,
    Item::Foil_Tag,
    Item::Holographic_Tag,
    Item::Polychrome_Tag,
    Item::Investment_Tag,
    Item::Voucher_Tag,
    Item::Boss_Tag,
    Item::Standard_Tag,
    Item::Charm_Tag,
    Item::Meteor_Tag,
    Item::Buffoon_Tag,
    Item::Handy_Tag,
    Item::Garbage_Tag,
    Item::Ethereal_Tag,
    Item::Coupon_Tag,
    Item::Double_Tag,
    Item::Juggle_Tag,
    Item::D6_Tag,
    Item::Top_up_Tag,
    Item::Speed_Tag,
    Item::Orbital_Tag,
    Item::Economy_Tag
};

std::vector<Item> BOSSES = {
    Item::The_Arm,
    Item::The_Club,
    Item::The_Eye,
    Item::Amber_Acorn,
    Item::Cerulean_Bell,
    Item::Crimson_Heart,
    Item::Verdant_Leaf,
    Item::Violet_Vessel,
    Item::The_Fish,
    Item::The_Flint,
    Item::The_Goad,
    Item::The_Head,
    Item::The_Hook,
    Item::The_House,
    Item::The_Manacle,
    Item::The_Mark,
    Item::The_Mouth,
    Item::The_Needle,
    Item::The_Ox,
    Item::The_Pillar,
    Item::The_Plant,
    Item::The_Psychic,
    Item::The_Serpent,
    Item::The_Tooth,
    Item::The_Wall,
    Item::The_Water,
    Item::The_Wheel,
    Item::The_Window
};